apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo_service
spec:
  selector:
    matchLabels:
      app: mongo_service
  template:
    metadata:
      labels:
        app: mongo_service
    spec:
      containers:
        - name: mongo
          image: mongo:5.0-focal
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: topoDB
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo_service
spec:
  type: ClusterIP
  selector:
    app: mongo_service
  ports:
    - port: 27019
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
spec:
  storageClassName: mongo-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: mongo-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"