apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-service
spec:
  selector:
    matchLabels:
      app: server-service
  template:
    metadata:
      labels:
        app: server-service
    spec:
      containers:
        - name: server-service
          image: adrian2606/eoloplannercommunications-server:version1
          env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: mysql
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mysql://mysql/eoloplantsDB
            - name: QUARKUS_DATASOURCE_USERNAME
              value: root
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: password
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: root
            - name: RABBITMQ_PASSWORD
              value: password
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server-service
  ports:
    - port: 9000